### ISSUE TITLE
Unable to login when LDAP entry is huge

### ISSUE THREAD

**Issue by jas01** [netmagis/netmagis#168]
I just found a bug pretty severe.

We use

  netmagis-common                2.3.3-1
  netmagis-database              2.3.3-1
  netmagis-utils                 2.3.3-1
  netmagis-www                   2.3.3-1

on a debian box.

The installation is fresh.

We use LDAP authentication.

If the givenname or diplayName or any other LDAP attribue (not the uid) contain a non ASCII character, like..utf-8, the user is
unable to login with a «Login failed due to an internal error » message

If I'm log with a non-utf-8 admin account and try a

    https://netmagis_URL/net?uid=uid_of_account_with_utf8

I got

    Authentication base problem: Protocol error: Error reading SEQUENCE response for handle ::ldap::ldapsock1afe660 : partial :

message.

So they are definitivly a bug about ldap connection when the response contain UTF-8 character

Regards

**Comment by pdav** [comment]
From the message, the problem seems to reside in the LDAP package of Tcllib. I will try to reproduce the problem.

**Comment by pdav** [comment]
With the help of Albert who provided an access to its LDAP directory, the bug has been traced down to the LDAPX package of Tcllib: it cannot decode the jpegPhoto attribute in a person LDAP entry (LDAPX assumes that all attributes are UTF-8 strings which is not the case for jpegPhoto).

**Comment by pdav** [comment]
The problem comes from a large response from the LDAP server, which is not properly decoded by the Tcllib LDAP interface.
The problem (with a patch) has been reported to Tcllib:
[https://core.tcl.tk/tcllib/tktview/c247ed5db42e373470bf8a6302717e76eb3c6106](https://core.tcl.tk/tcllib/tktview/c247ed5db42e373470bf8a6302717e76eb3c6106)

A workaround should be integrated in Netmagis while waiting for the next Tcllib version. In the meanwhile, applying the proposed patch to the installed ldap/ldap.tcl (from the tcllib Debian/FreeBSD package) solves the problem if one encounters it.

The problem is not related to UTF-8 decoding (happily).

**Comment by pdav** [comment]
The last version of Tcllib (1.19, see [https://sourceforge.net/projects/tcllib/files/tcllib/1.19/](https://sourceforge.net/projects/tcllib/files/tcllib/1.19/)) includes our patch (see [https://core.tcl.tk/tcllib/info/c247ed5db4](https://core.tcl.tk/tcllib/info/c247ed5db4)).

**Comment by pdav** [comment]
A work-around is installed in the up-coming 2.3.5 release.
