### ISSUE TITLE
No bump of the serial

### ISSUE THREAD

**Issue by jas01** [netmagis/netmagis#178]
The serial isn't bump when we change the prolog of a zone. 
So that can be very disturbing when you change the ( for example )
`IN MX`
So only solution is to add something and delete something.

**Comment by pdav** [comment]
Serial should change automatically when a zone prologue is modified, since there is a trigger on the dns.zone* tables. Please, check these triggers. You should have:
```
netmagis=> \d dns.zone_forward
...
Triggers:
    tr_mod_zone BEFORE UPDATE ON dns.zone_forward FOR EACH ROW EXECUTE PROCEDURE dns.mod_zone()
```
(the same apply for `dns.zone_reverse4` and `dns.zone_reverse6` tables).

If triggers are not here (why? May be a previous update which failed?), you can reset them with:
```
psql --no-psqlrc --single-transaction -f ......./lib/triggers.sql netmagis
```

**Comment by pdav** [comment]
Any news on this issue?

**Comment by pdav** [comment]
No news on this issue. Close it.
